### PR TITLE
330 update

### PR DESCRIPTION
**Pull request by scorninpc**
update!

### CODE REVIEW

**Comment by elfennani** [comment]
The game unfortunately doesn't launch for me.

**Comment by akbarfa49** [comment]
> The game unfortunately doesn't launch for me.

um, u need to remove an  "exit 0" on sh script before applying patch if u haven't do it

**Comment by elfennani** [comment]
I know, I already removed it

**Comment by elfennani** [comment]
Which wine version are you using?

**Comment by akbarfa49** [comment]
> Which wine version are you using?

lutris-7.2-2-x86_64 and international version of genshin.
have u apply the patch_anti_login_crash? (in my case i don't need this anyway)

i think u can try upload your log too?

maybe we can move to the issue page
https://github.com/zeroday0619/MyLittleLutrisScripts/issues/4

**Comment by elfennani** [comment]
Fixed no need to open an issue, I was running an old wine version.

**Review by ezequielramos — APPROVED** [review]

**Comment by scorninpc** [comment]
@ezequielramos i've committed another one without "exit"s for tomorrow, when it will be launched officially

**Review by ezequielramos — APPROVED** [review]

**Review by zeroday0619 — APPROVED** [review]

**Comment by zeroday0619** [comment]
may be merged based on KST (UTC+9) timezone.
@scorninpc

**Pull request closed without merging**
